add information about what is set up after each step
magicaks/magicaks pull request #113
Opened 2021-03-11 16:02 UTC by TessFerrandez

This PR closes #69 by listing the resources provisioned after each step

2021-03-11 16:03 UTC, TessFerrandez commented on setup.md
> +    * Subnet: **snet-adhoc**
Note: I don't know what this subnet is used for

2021-03-15 10:11 UTC, tompaana requested changes
I suggest style changes. It is a matter of opinion so if you disagree, reject and I'll approve.

2021-03-15 10:11 UTC, tompaana commented on setup.md
> +* environment variables set - for running the terraform scripts
```suggestion
After this section you should have the following resources created:

* Azure AD group called `magicaksadmins`
* Service principal, `magicaks-terraform`, for provisioning resources
* Service principal, `magicaks-grafana`, for operating Grafana
* Azure storage for Terraform state
  * Resource group: `rg-terraform-state`
    * Storage account: `tfstate[random]`
      * Storage container: `tfstate`
* Environment variables set for running the Terraform scripts
```

2021-03-15 10:11 UTC, tompaana commented on setup.md
> +* environment variables set - for running the terraform scripts
The emphasis (bold style) on the names of the resources does not make sense to me. I see this is the pattern in other changes too. My personal preference would be to as in my suggestion.

2021-03-15 10:11 UTC, tompaana commented on setup.md
> +* Key vault secrets:
```suggestion
* Key Vault secrets:
```

2021-03-15 10:21 UTC, Lybecker commented
Would it make sense to have screenshots of the Azure portal showing the resources created?

2021-03-15 12:08 UTC, TessFerrandez commented
> Would it make sense to have screenshots of the Azure portal showing the resources created?

I'll add some screen shots...

2021-03-16 10:12 UTC, christoferlof commented on setup.md
> +    * Subnet: **snet-adhoc**
@sachinkundu is it safe to remove the adhoc subnet?

2021-03-17 07:56 UTC, tompaana approved these changes

2021-03-17 08:38 UTC, sachinkundu commented on setup.md
> +    * Subnet: **snet-adhoc**
no its used for example to add bastion box

2021-03-17 09:37 UTC, merged