Update Readme after first pass of setup
magicaks/magicaks pull request #55
Opened 2021-02-22 15:21 UTC by TessFerrandez

- Clean up typos
- General rewording of steps - clarification etc. to make it a bit easier to go through
- Added todos comments in the draft - these will be removed before merging the PR.

2021-02-22 16:13 UTC, sachinkundu commented
Looks good! Let's merge when done and go from there. Let's ask someone else to run through it and revaluate after that.

2021-02-23 11:49 UTC, Lybecker approved these changes

2021-02-23 11:49 UTC, Lybecker commented on setup.md
> +* [kubectl min version 1.18.1](https://kubernetes.io/docs/tasks/tools/install-kubectl/)
This step is not needed anymore, as it is installed via AZ cli

2021-02-23 11:49 UTC, Lybecker commented on setup.md
> +[TODO]: # (is this correct?)
Yes. We need that stuff. @sachinkundu can you describe what is needed?

2021-02-23 11:49 UTC, Lybecker commented on setup.md
> +    STORAGE_ACCOUNT_NAME=tstate$RANDOM
Where does the @RANDOM comes from?

2021-02-23 11:49 UTC, Lybecker commented on setup.md
> +    az group create --name $RESOURCE_GROUP_NAME --location eastus
Hard-coded location

2021-02-23 11:49 UTC, Lybecker commented on setup.md
> +> NOTE: It's normal for this to take a long time to provision, especially the Firewall, so relax and grab a coffee.
I ❤️ this :)

2021-02-23 11:49 UTC, Lybecker commented on setup.md
> +    export registry=registry_name_here
Description: registry_name_here var is the name of the Azure Container Registry created during pre-provisioning.

2021-02-23 11:49 UTC, Lybecker commented on setup.md
> +    [TODO]: # (figure out what this is and which variable we are talking about)
MSI_RESOURCE_ID is the Managed Identity created above. The AKS cluster will use this identity when accsing other resource like ACR, Key Vault etc.

2021-02-23 12:08 UTC, TessFerrandez commented on setup.md
> +[TODO]: # (is this correct?)
ahh, the "is this correct was for the line below" i.e. "you can do everything in this section once, and reuse the assets when spinning up new AKS clusters"

2021-02-23 12:09 UTC, TessFerrandez commented on CONTRIBUTING.md
>  * Ask [Sachin Kundu](mailto:skundu@hey.com)
I will remove this part for now - since we already have a section about opening a new issue

2021-02-23 12:10 UTC, TessFerrandez commented on README.md
> +When needed, the solution uses open source tooling like [kured](https://github.com/weaveworks/kured).
I will add an issue to look over the tools we use and add them

2021-02-23 12:16 UTC, TessFerrandez commented on README.md
> -Instead of writing k8s manifests directly we use Fabrikate HLD to write the config which is then translated to K8s manifests using a pipeline which in turn runs ``fab generate`` and pushes the config
Removed this

2021-02-23 12:25 UTC, TessFerrandez commented on setup.md
> +    STORAGE_ACCOUNT_NAME=tstate$RANDOM
$RANDOM gives a random number - so the storage is unique

2021-02-23 12:25 UTC, TessFerrandez commented on setup.md
> +    az group create --name $RESOURCE_GROUP_NAME --location eastus
Fixing

2021-02-23 12:28 UTC, TessFerrandez commented on setup.md
> +    export registry=registry_name_here
adding this

2021-02-23 12:30 UTC, TessFerrandez commented on setup.md
> +    [TODO]: # (figure out what this is and which variable we are talking about)
fixing

2021-02-23 12:34 UTC, tompaana requested changes

2021-02-23 12:34 UTC, tompaana commented on setup.md
> +* [Azure CLI](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest) logged in with a user with permissions to provision resources and create applications on the AAD.
```suggestion
* [Azure CLI](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest) [logged in](https://docs.microsoft.com/en-us/cli/azure/authenticate-azure-cli) with a user with permissions to provision resources in Azure and manage [Azure Active Directory (AAD)](https://azure.microsoft.com/en-us/services/active-directory/).
```

2021-02-23 12:34 UTC, tompaana commented on setup.md
> +* [Terraform](https://www.terraform.io/downloads.html) Tested with v0.14.2
```suggestion
* [Terraform](https://www.terraform.io/downloads.html) (tested with version 0.14.2)
```

2021-02-23 12:34 UTC, tompaana commented on setup.md
> +You can also use this [Docker dev container](./utils/docker-dev-env/README.md) if you don't want to install the tools on your own machine.
```suggestion
You can also use this [Docker dev container](./utils/docker-dev-env/README.md), if you don't want to install the tools in your native environment, but note that there can be additional considerations using the Docker development environment that are not covered by this guide.
```

2021-02-23 12:34 UTC, tompaana commented on setup.md
> +> **NOTE:** The installation assumes that you have an Azure Active Directory, and that you are the owner/admin of this directory or can request to create AAD apps. We will need this for RBAC setup fo
```suggestion
> **Note:** The installation assumes that you have an Azure Active Directory (AAD), and that you are the owner/admin of this directory or can request to create AAD apps. We will need this for [role-based access control (RBAC)](https://docs.microsoft.com/en-us/azure/role-based-access-control/overview) setup for Kubernetes. For testing purposes you can [create a personal AAD](https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/active-directory-access-create-new-tenant).
```

2021-02-23 12:34 UTC, tompaana commented on setup.md
> +Before provisioning the AKS resources we need to prepare some repositories, set up AAD security groups and Service Principals.
```suggestion
Before provisioning the AKS resources we need to prepare some repositories, set up AAD security groups and service principals.
```

2021-02-23 12:34 UTC, tompaana commented on setup.md
> +[Duplicate](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/duplicating-a-repository) this repository in GitHub and make your repository private. You will need to change
```suggestion
[Duplicate](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/duplicating-a-repository) this repository in GitHub and make your repository private. You will need to change some of the Terraform scripts etc. throughout this setup.
```

2021-02-23 12:34 UTC, tompaana commented on setup.md
> +1. Log in as AAD admin.
```suggestion
1. Log in as AAD admin:
```

2021-02-23 12:34 UTC, tompaana commented on setup.md
> +    > NOTE: You need to log in on tenant that you want to manage RBAC from - to login in to a specific tenant use `az login --tenant <tenant_id>` and if your AAD tenant does not have a subscription,
```suggestion
    > **Note:** You need to log in on tenant that you want to manage RBAC from - to login into a specific tenant use `az login --tenant <tenant_id>` and if your AAD tenant does not have a subscription, run `az login --tenant <tenant_id> --allow-no-subscriptions` instead.
```

2021-02-23 12:34 UTC, tompaana commented on setup.md
> +2. Create a new Azure AD group for the AKS cluster admins
```suggestion
2. Create a new Azure AD group for the AKS cluster admins:
```

2021-02-23 12:34 UTC, tompaana commented on setup.md
> +1. Log in as AAD admin.
Nit: Perhaps just stick to using "1." for all the items in the ordered list (unless something in the Markdown breaks the automatic numbering).

2021-02-23 12:34 UTC, tompaana commented on setup.md
> +1. Duplicate the [fabricate-defs repository](https://github.com/magicaks/fabrikate-defs). We recommended making this repository private.
```suggestion
1. Duplicate the [Fabrikate high-level definitions (HLD) repository](https://github.com/magicaks/fabrikate-defs). We recommended making this repository private. You will use this repository, for example, to generate RBAC and Azure Monitor configuration.
```

2021-02-23 12:34 UTC, tompaana commented on setup.md
> +    This will be your Fabrikate High Level Definition (HLD) repo.
```suggestion
```

2021-02-23 12:34 UTC, tompaana commented on setup.md
> +    You will use this repository to generate RBAC and Azure Monitor configuration
```suggestion
```

2021-02-23 12:34 UTC, tompaana commented on setup.md
> +2. Follow the steps in the [README](https://github.com/magicaks/fabrikate-defs/blob/master/README.md) to set up RBAC for your cluster.
```suggestion
2. Follow the steps in the [Fabrikate definitions repository README](https://github.com/magicaks/fabrikate-defs/blob/master/README.md) to set up RBAC for your cluster.
```

2021-02-23 12:34 UTC, tompaana commented on setup.md
> +> **NOTE:** Make sure you finish the steps in the README before you continue
```suggestion
> **Note:** Make sure you finish the steps in the README before you continue.
```

2021-02-23 12:34 UTC, tompaana commented on setup.md
> +This is user workloads manifest repo where you list non-privileged workloads. Flux gitOps non admin controller will track this repository.
```suggestion
This is user workloads manifest repo where you list non-privileged workloads. [Flux (GitOps)](https://fluxcd.io/) non-admin controller will track this repository.
```

2021-02-23 12:34 UTC, tompaana commented on setup.md
> +### 5. Create Service Principals for provisioning resources
```suggestion
### 5. Create service principals for provisioning resources
```

2021-02-23 12:34 UTC, tompaana commented on setup.md
> +1. Create a service principal (**terraform-magicaks**) that terraform can use for deploying resources. **Write down the id and password for later.**
```suggestion
1. Create a service principal (**terraform-magicaks**) that Terraform can use for deploying resources and make sure to **write down the ID and password for later**:
```

2021-02-23 12:34 UTC, tompaana commented on setup.md
> +    > **NOTE:** Replace SUBSCRIPTION_ID with your own Azure subscription ID
```suggestion
    > **Note:** Replace `SUBSCRIPTION_ID` with your own Azure subscription ID.
```

2021-02-23 12:34 UTC, tompaana commented on setup.md
> +2. Create a service principal (**magicaks-grafana**) that grafana can use for talking to log analytics backend. We restrict this service principal to **Monitoring Reader**.
```suggestion
2. Create a service principal (**magicaks-grafana**) that Grafana can use for talking to Log Analytics backend. We restrict this service principal to **Monitoring Reader** role.
```

2021-02-23 12:34 UTC, tompaana commented on setup.md
> +1. Create a service principal (**terraform-magicaks**) that terraform can use for deploying resources. **Write down the id and password for later.**
Note for later: We should be consistent with naming and change this to "magicaks-terraform".

2021-02-23 12:34 UTC, tompaana commented on setup.md
> +1. If you don't have a storage account to use for terraform state already configured. Create a resource group and a storage account with a container per the instructions from the Microsoft docs [Tuto
```suggestion
1. If you don't have a storage account to use for Terraform state already configured, create a resource group and a storage account with a container per the instructions from the Microsoft docs: [Tutorial: Store Terraform state in Azure Storage](https://docs.microsoft.com/en-us/azure/developer/terraform/store-state-in-azure-storage):
```

2021-02-23 12:34 UTC, tompaana commented on setup.md
> +3. Update the terraform section of [1-preprovision/main.tf](1-preprovision/main.tf) with your values for resource_group_name, container_name, and storage_account_name. Leave the key as **"magicaks-lo
```suggestion
3. Update the Terraform section of [1-preprovision/main.tf](./1-preprovision/main.tf) with your values for `resource_group_name`, `container_name`, and `storage_account_name`. Leave the key as `**"magicaks-longlasting"**`.
```

2021-02-23 12:34 UTC, tompaana commented on setup.md
> +### 7. Set up the environment variables for terraform
```suggestion
### 7. Set up the environment variables for Terraform
```

2021-02-23 12:36 UTC, TessFerrandez commented on setup.md
> +* [kubectl min version 1.18.1](https://kubernetes.io/docs/tasks/tools/install-kubectl/)
Removed kubectl - per Anders comment that we are not using it anymore - so skipping this

2021-02-23 12:37 UTC, TessFerrandez commented on setup.md
> +We have tested this repo with OSX, Linux and Windows (on [WSL](https://docs.microsoft.com/en-us/windows/wsl/)).
will fix

2021-02-23 12:52 UTC, Lybecker commented on setup.md
> +    STORAGE_ACCOUNT_NAME=tstate$RANDOM
I don't think you want a random storage account name. Then the TerraForm state will be in different location everytime you run the script?

2021-02-23 13:05 UTC, tompaana requested changes

2021-02-23 13:05 UTC, tompaana commented on setup.md
> +7. Pod security policies enabled and a restricted policy added.
```suggestion
* Pod security policies enabled and a restricted policy added
```

2021-02-23 13:05 UTC, tompaana commented on setup.md
> +7. Pod security policies enabled and a restricted policy added.
Hold on a minute, buster! Just before you told me that "AKS has deprecated PSP in favor of Azure Policy". What kind of shenanigans are you pulling here?

2021-02-23 13:05 UTC, tompaana commented on setup.md
> +8. Azure Policy enabled on the cluster. No policies assigned right now.
```suggestion
* Azure Policy enabled on the cluster (no policies assigned right now)
```

2021-02-23 13:05 UTC, tompaana commented on setup.md
> +9. Azure Firewall integrated with network and application rules as recommended by AKS.
```suggestion
* Azure Firewall integrated with network and application rules as recommended by AKS
```

2021-02-23 13:05 UTC, tompaana commented on setup.md
> +10. Grafana connected to log analytics workspace of the cluster is running in Azure container instance backed by managed Postgresql Azure database.
```suggestion
* Grafana connected to Log Analytics workspace of the cluster is running in Azure Container Instances backed by managed PostgreSQL database
```

2021-02-23 13:05 UTC, tompaana commented on setup.md
> +   5. Calico as the network plugin
```suggestion
   * Calico as the network plugin
```

2021-02-23 13:05 UTC, tompaana commented on setup.md
> +   6. Kubernetes version = 1.19.7
```suggestion
   * Kubernetes version = 1.19.7
```

2021-02-23 13:23 UTC, TessFerrandez commented on setup.md
> +   2. Container insights in enabled.
will add this

2021-02-23 13:23 UTC, TessFerrandez commented on setup.md
> +7. Pod security policies enabled and a restricted policy added.
I'll add an issue about this

2021-02-23 13:29 UTC, tompaana approved these changes

2021-02-23 13:29 UTC, merged